### ISSUE TITLE
Pydantic V2 support

### ISSUE THREAD

**Issue by logan-markewich** [Preemo-Inc/gradientai-python-sdk#23]
Can we add support for pydantic V2? Even by using their v1 compatibility layer? It causes some packaging issues downstream

**Comment by linjer** [comment]
@michaelfeil @atmiguel @mhaligowski Would you be able to help get #27 merged?

**Comment by ofek** [comment]
It would be great to get these conflicts resolved!

**Comment by masci** [comment]
Related: latest version 1.12.0 made Haystack test fail on Python 3.9 with `TypeError: dataclass() got an unexpected keyword argument 'kw_only'`, most likely caused by https://github.com/Preemo-Inc/gradientai-python-sdk/pull/28/files#diff-3733539533707a7044af4c5ead69949bf1e3fff5cc271c605b82287acc11fb8fR22

Link to failing CI: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/9039411463

**Comment by mhaligowski** [comment]
@masci thanks, I missed that `kw_only` was added in 3.10... version 1.12.1 is live!

**Comment by linjer** [comment]
It seems maintainers have no interest in addressing this. I will likely resolve this by removing dependency.

**Comment by linjer** [comment]
@ml2 Appreciate the update! I'll close out my PR.

**Comment by ml2** [comment]
We have deployed the change allowing customers above 1.10.15 to use V1 and the rest to use V2. Let us know if you have any issues
